spring:
  cloud:
    openfeign:
      client:
        config:
          airports:
            url: "http://localhost:3000"
          default:
            connectTimeout: 5000
            readTimeout: 5000
            gerLevel: basic
