package com.klm.itinerary.model;

public enum IATA {
    AAL,AAR,ABZ,ACC,ACE,AES,AGP,ALC,AMM,AMS,ARN,ATH,ATL,AUA,AUH,AUS,BAH,BCN,BEG,BER,BEY,BGI,BGO,BHD,BHX,BIO,BKK,BLL,BLQ,BLR,BOD,BOG,BOJ,BOM,BON,BOS,BRE,BRI,BRS,BRU,BSL,BUD,CAG,CAN,CDG,CFU,CGK,CHQ,CMN,CPH,CPT,CTA,CTG,CUN,CUR,CWL,DAR,DBV,DEL,DMM,DPS,DRS,DTW,DUB,DUS,DXB,EBB,EDI,EFL,EZE,FAO,FCO,FLR,FNC,FRA,FUE,GDN,GIG,GLA,GOA,GOT,GRO,GRU,GRZ,GUA,GVA,GYE,HAJ,HAM,HEL,HER,HKG,HRE,HRG,HUY,IAD,IAH,IBZ,ICN,INN,INV,IST,JFK,JMK,JNB,JRO,JTR,KBP,KEF,KGL,KGS,KIX,KLX,KRK,KRS,KTW,KUL,KWI,LAS,LAX,LBA,LCA,LCY,LED,LHR,LIM,LIN,LIR,LIS,LJU,LOS,LPA,LPI,LUX,LYS,MAD,MAH,MAN,MCO,MCT,MEX,MIA,MLA,MME,MNL,MPL,MRS,MSP,MUC,MXP,NAP,NBO,NCE,NCL,NRT,NTE,NUE,NWI,OLB,OPO,ORD,ORK,ORY,OSL,OTP,PBM,PDX,PEK,PFO,PKX,PMI,POS,POZ,PRG,PSA,PTY,PVG,PVK,RAK,RHO,RIX,RNS,RUH,RVN,SCL,SEA,SFO,SIN,SJO,SKG,SLC,SMI,SOU,SPC,SPU,SSH,STR,SVG,SVO,SVQ,SXM,SZG,TBS,TFS,TLS,TLV,TOS,TPE,TRD,TRF,TRN,UIO,VCE,VCP,VIE,VLC,VRN,WAW,WRO,XMN,YEG,YUL,YVR,YYC,YYZ,ZAG,ZNZ,ZRH,ZTH
}
